/*
 * generated by Xtext 2.25.0
 */
package hu.bme.mit.mdsd.recipe.text

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RecipeDslStandaloneSetup extends RecipeDslStandaloneSetupGenerated {

	def static void doSetup() {
		new RecipeDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
